<?php
/** @file
 *
 * ScaffoldNewBundle is a BaseFortissimoCommand class.
 *
 * Created by Matt Butcher on 2011-06-15.
 */
namespace Villain\Bundles;
/**
 * Scaffold a new bundle.
 *
 * This programmatically creates a new bundle. Since this creates not only
 * files and directories, but actually executable files, it should be used
 * with extreme caution. It is recommended that this be used with `fort`
 * and similar CLI programs, but not from within the webapp.
 *
 * Note that whatever user executes PHP will need to have write permissions to bundles/
 * in order for this to work.
 *
 * @author Matt Butcher
 */
class ScaffoldNewBundle extends \BaseFortissimoCommand {

  public function expects() {
    return $this
      ->description('Create a new bundle')
      ->usesParam('name', 'The name of the new bundle to create.')
      ->withFilter('string')
      ->whichIsRequired()
      
      ->andReturns('Boolean value indicating success (TRUE) or failure (FALSE)')
    ;
  }

  public function doCommand() {
    
    $bundleName = $this->param('name');
    if (empty($bundleName)) {
      throw new \Villain\InterruptException('Bundle name cannot be empty.');
    }
    
    if (!Bundle::isValidName($bundleName)) {
      throw new \Villain\InterruptException('Illegal bundle name: ' . $bundleName);
    }
    
    $path = $this->createBundleDirectory($bundleName);
    $this->createBundleSubdirectories($path);
    $this->createBundlePHP($path, $bundleName);
    

    return TRUE;
  }
  
  protected function createBundleDirectory($name) {
    $path = Bundle::DIR . $name;
    if (!is_dir(Bundle::DIR)) {
      throw new \Villain\InterruptException('No bundle directory found at ' . Bundle::DIR);
    }
    
    if (!is_writable(Bundle::DIR)) {
      throw new \Villain\InterruptException('Permission error: Cannot write to ' . Bundle::DIR);
    }
    
    if (file_exists($path)) {
      throw new \Villain\InterruptException('Bundle already exists at ' . $path);
    }
    
    mkdir($path);
    
    return $path;
  }
  
  protected function createBundleSubdirectories($path) {
    mkdir($path . '/src');
    mkdir($path . '/test');
    mkdir($path . '/doc');
    mkdir($path . '/media');
    mkdir($path . '/media/css');
    mkdir($path . '/media/img');
    mkdir($path . '/media/js');
  }
  
  protected function createBundlePHP($path, $name) {
    $klass = __CLASS__;
    $code =<<<EOF
<?php
use \Villain\Bundles\Bundle;

Bundle::create('$name')
  ->description('Autogenerated by $klass. Change this.')
  ->version('1.0.0');
EOF;
    $f = fopen($path . '/bundle.php', 'w');
    fwrite($f, $code);
    fclose($f);
  }
}

